apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Bucket
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cos4seedb-bucket-jadeyliu-m2c711
spec:
  apiKey:
    secretKeyRef:
      name: cos4seed-hmac
      key: apikey
  resourceInstanceID:
    secretKeyRef:
      name: cos4seed-hmac
      key: resource_instance_id
  endpoints:
    configMapKeyRef:
      name: cos4seed-hmac
      key: endpoints
  keyProtect:
     instanceID: 89730538-2c9f-4f74-b861-6f1f8873f3cd
     keyName: forcos4seedb
     apiKey:
       secretKeyRef:
         name: ibmcloudapikey
         key: apikey
