apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app.kubernetes.io/name: cos-bucket-operator
  name: cos-bucket-operator
  namespace: cos-bucket-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cos-bucket-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cos-bucket-operator
    spec:
      containers:
      - args: null
        command:
        - ./manager
        image: cloudoperators/cosbucket-operator:0.1.0
        imagePullPolicy: Always
        name: cos-bucket-controller
      serviceAccountName: cos-bucket-operator
