# Constants used to package the operator for operator hub

operator_name: cos-bucket-operator
channel_name: alpha
maturity: alpha
image: cloudoperators/cosbucket-operator
crd:
    - kind: Bucket
      description: Represents a bucket of a Cloud Object Storage bucket resource  on IBM Cloud.
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
            "kind": "Bucket",
            "metadata": {
            "name": "cos4seed-bucket-m2c711"
            }
        }
      resources:
        - kind: Secret
          version: v1
        - kind: ConfigMap
          version: v1  
        - kind: Bucket
          version: v1alpha1
      specDescriptors: 
        - description: API Key
          displayName: API Key
          path: apiKey
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Endpoints
          displayName: Endpoints
          path: endpoints
          x-descriptors:
            - 'urn:alm:descriptor:text'  
        - description: Resource Instance ID
          displayName: Resource Instance ID
          path: resourceInstanceID
          x-descriptors:
            - 'urn:alm:descriptor:text'
      statusDescriptors:
        - description: Detailed message on current status
          displayName: Message
          path: message
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Current plan for service
          displayName: Plan
          path: plan
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Current service class
          displayName: Service Class
          path: serviceClass
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Indicates if IAM type or legacy
          displayName: Service Class Type
          path: serviceClassType
          x-descriptors:
            - 'urn:alm:descriptor:text'  
        - description: Current state for the service
          displayName: State
          path: state
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Current context for the service (resorce group, region, org, space)
          displayName: Context
          path: context
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Instance ID for the service
          displayName: Instance ID
          path: instanceId
          x-descriptors:
            - 'urn:alm:descriptor:text'      